#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android.Widget.Extras.Resource", IsApplication=false)]

namespace Android.Widget.Extras
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int fab_backgroundColor = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int fab_content = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int fab_radius = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int fab_shadowColor = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f020000
			public static int shadow_color = 2130837504;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030001
			public static int padding = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int radius = 2130903040;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 2
			public static int FloatingActionButton_fab_backgroundColor = 2;
			
			// aapt resource value: 0
			public static int FloatingActionButton_fab_content = 0;
			
			// aapt resource value: 1
			public static int FloatingActionButton_fab_radius = 1;
			
			// aapt resource value: 3
			public static int FloatingActionButton_fab_shadowColor = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
