#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Android.FloatingActionButton.Sample.Resource", IsApplication=true)]

namespace Xamarin.Android.FloatingActionButton.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Android.Widget.Extras.Resource.Attribute.fab_backgroundColor = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Attribute.fab_backgroundColor;
			global::Android.Widget.Extras.Resource.Attribute.fab_content = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Attribute.fab_content;
			global::Android.Widget.Extras.Resource.Attribute.fab_radius = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Attribute.fab_radius;
			global::Android.Widget.Extras.Resource.Attribute.fab_shadowColor = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Attribute.fab_shadowColor;
			global::Android.Widget.Extras.Resource.Color.shadow_color = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Color.shadow_color;
			global::Android.Widget.Extras.Resource.Dimension.padding = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Dimension.padding;
			global::Android.Widget.Extras.Resource.Dimension.radius = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Dimension.radius;
			global::Android.Widget.Extras.Resource.String.ApplicationName = global::Xamarin.Android.FloatingActionButton.Sample.Resource.String.ApplicationName;
			global::Android.Widget.Extras.Resource.String.Hello = global::Xamarin.Android.FloatingActionButton.Sample.Resource.String.Hello;
			global::Android.Widget.Extras.Resource.Styleable.FloatingActionButton = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Styleable.FloatingActionButton;
			global::Android.Widget.Extras.Resource.Styleable.FloatingActionButton_fab_backgroundColor = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Styleable.FloatingActionButton_fab_backgroundColor;
			global::Android.Widget.Extras.Resource.Styleable.FloatingActionButton_fab_content = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Styleable.FloatingActionButton_fab_content;
			global::Android.Widget.Extras.Resource.Styleable.FloatingActionButton_fab_radius = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Styleable.FloatingActionButton_fab_radius;
			global::Android.Widget.Extras.Resource.Styleable.FloatingActionButton_fab_shadowColor = global::Xamarin.Android.FloatingActionButton.Sample.Resource.Styleable.FloatingActionButton_fab_shadowColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int fab_backgroundColor = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int fab_content = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int fab_radius = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int fab_shadowColor = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int DodgerBlue = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int shadow_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int padding = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int radius = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_new = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int dummyList = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int fab = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int layout = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int BaseAppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_backgroundColor = 2;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_content = 0;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_radius = 1;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_shadowColor = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
